# Generated by Django 5.0.6 on 2024-05-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('id_number', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=20)),
                ('married', models.BooleanField()),
                ('city', models.CharField(max_length=30)),
                ('birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
